/**
 * Extract raw glyph bitmaps from a Windows .FON bitmap font.
 *
 * A .FON is a 16-bit NE executable whose resources include one or more FNT
 * bitmap fonts. We want the raw bits — 256 glyphs x 16 rows x 1 byte for an
 * 8x16 font — so the renderer can blit pixels directly instead of asking the
 * browser to draw text. Canvas `fillText` antialiases and hints regardless of
 * settings, which would put glyphs on fractional pixels and defeat the whole
 * point of a pixel-exact rebuild.
 *
 *   node tools/extract-font.js "font/fon - Bm (windows bitmap)/Bm437_IBM_VGA_8x16.FON" src/render/font-data.js
 */
import { readFileSync, writeFileSync } from 'node:fs';

const RT_FONT = 0x8008;

function parseNeResources(buf) {
  if (buf.readUInt16LE(0) !== 0x5a4d) throw new Error('not an MZ executable');
  const neOff = buf.readUInt32LE(0x3c);
  if (buf.toString('latin1', neOff, neOff + 2) !== 'NE') throw new Error('not an NE executable');

  const rsrcOff = neOff + buf.readUInt16LE(neOff + 0x24);
  const shift = buf.readUInt16LE(rsrcOff);
  const out = [];
  let p = rsrcOff + 2;
  for (;;) {
    const typeId = buf.readUInt16LE(p);
    if (typeId === 0) break;
    const count = buf.readUInt16LE(p + 2);
    p += 8;
    for (let i = 0; i < count; i++) {
      const offset = buf.readUInt16LE(p) << shift;
      const length = buf.readUInt16LE(p + 2) << shift;
      if (typeId === RT_FONT) out.push({ offset, length });
      p += 12;
    }
  }
  return out;
}

/** Parse an FNT resource into fixed-size glyph bitmaps. */
function parseFnt(buf, base) {
  const u8 = (o) => buf.readUInt8(base + o);
  const u16 = (o) => buf.readUInt16LE(base + o);
  const u32 = (o) => buf.readUInt32LE(base + o);

  const version = u16(0);
  const pixWidth = u16(86);
  const pixHeight = u16(88);
  const firstChar = u8(95);
  const lastChar = u8(96);

  if (pixWidth !== 8) {
    throw new Error(`expected an 8-pixel-wide font, got ${pixWidth}`);
  }

  // dfCharTable: v2 entries are {width:u16, offset:u16}, v3 {width:u16, offset:u32}.
  const entrySize = version >= 0x300 ? 6 : 4;
  const nEntries = lastChar - firstChar + 2; // includes the sentinel entry
  const glyphs = new Uint8Array(256 * pixHeight);

  for (let i = 0; i < nEntries - 1; i++) {
    const e = 118 + i * entrySize;
    const width = u16(e);
    const off = entrySize === 6 ? u32(e + 2) : u16(e + 2);
    if (width === 0 || off === 0) continue;
    const code = firstChar + i;
    if (code > 255) break;
    // For an 8-wide glyph there is one column of `pixHeight` bytes, top to bottom.
    for (let row = 0; row < pixHeight; row++) {
      glyphs[code * pixHeight + row] = buf.readUInt8(base + off + row);
    }
  }

  return { version, pixWidth, pixHeight, firstChar, lastChar, glyphs };
}

const [, , src, dest] = process.argv;
if (!src) {
  console.error('usage: node tools/extract-font.js <font.FON> [out.js]');
  process.exit(2);
}

const buf = readFileSync(src);
const resources = parseNeResources(buf);
if (!resources.length) throw new Error('no RT_FONT resources found');

const font = parseFnt(buf, resources[0].offset);
console.log(
  `FNT v${font.version.toString(16)}  ${font.pixWidth}x${font.pixHeight}  ` +
  `chars ${font.firstChar}..${font.lastChar}  ${font.glyphs.length} bytes`
);

// Sanity check: 'A' (0x41) should be non-blank and vertically centred-ish.
const A = Array.from(font.glyphs.slice(0x41 * font.pixHeight, 0x42 * font.pixHeight));
console.log('glyph 0x41 "A":');
for (const row of A) {
  console.log('  ' + row.toString(2).padStart(8, '0').replace(/0/g, '.').replace(/1/g, '#'));
}
if (A.every((b) => b === 0)) throw new Error('glyph A is blank — extraction failed');

if (dest) {
  const b64 = Buffer.from(font.glyphs).toString('base64');
  const js = `/**
 * IBM VGA 8x${font.pixHeight} bitmap font, codepage 437.
 *
 * Generated by tools/extract-font.js from VileR's Ultimate Oldschool PC Font
 * Pack (int10h.org). Do not edit by hand.
 *
 * Layout: 256 glyphs x ${font.pixHeight} rows x 1 byte. Bit 7 is the leftmost
 * pixel. Glyph N occupies bytes [N * ${font.pixHeight}, (N + 1) * ${font.pixHeight}).
 */
export const GLYPH_WIDTH = ${font.pixWidth};
export const GLYPH_HEIGHT = ${font.pixHeight};

const PACKED =
  '${b64}';

export const FONT = Uint8Array.from(atob(PACKED), (c) => c.charCodeAt(0));
`;
  writeFileSync(dest, js);
  console.log(`wrote ${dest}`);
}
