/**
 * Generate the embedded demo plan from a real one.
 *
 * The demo needs to be a *real* pattern — 260 holes with dummies, benches, a
 * boundary and a proper tie-up exercise every calculation in a way a generated
 * grid does not. But the plan it comes from is a customer's 1992 blast, and its
 * survey coordinates locate an actual quarry.
 *
 * So the geometry is kept and the identity removed: every coordinate is
 * translated so the pattern's south-west corner sits at the origin, and the
 * title is replaced. Shape, spacing, depths, timing and tie-up are untouched,
 * which is everything that makes it useful as a demonstration. Nothing that
 * survives says where it is.
 *
 *   node tools/make-demo.js [source.XEL]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { parseXel } from '../src/format/xel.js';
import { writeXel } from '../src/format/xel-write.js';

const src = process.argv[2] ?? 'samples/TEST4.XEL';
const bytes = new Uint8Array(readFileSync(src));
let text = '';
for (let i = 0; i < bytes.length; i++) text += String.fromCharCode(bytes[i]);

const plan = parseXel(text);

// Translate so the pattern starts at the origin.
let minE = Infinity, minN = Infinity;
const pts = [
  ...plan.holes.filter((h) => !h.deleted && h.e !== null),
  ...plan.benches.flatMap((b) => [...b.crest, ...b.foot]),
  ...plan.boundary,
  ...plan.texts,
];
for (const p of pts) {
  if (p.e !== null && p.e < minE) minE = p.e;
  if (p.n !== null && p.n < minN) minN = p.n;
}
const shift = (p) => {
  if (p.e !== null) p.e -= minE;
  if (p.n !== null) p.n -= minN;
};
for (const p of pts) shift(p);
plan.extents = {
  minE: plan.extents.minE - minE, maxE: plan.extents.maxE - minE,
  minN: plan.extents.minN - minN, maxN: plan.extents.maxN - minN,
};

plan.title = 'DEMO PATTERN';

const out = writeXel(plan);
const js = `/**
 * Embedded demo plan — a real 260-hole pattern with its identity removed.
 *
 * Generated by tools/make-demo.js. Geometry, depths, tie-up and timing are
 * genuine, which is what makes every calculation worth looking at. Coordinates
 * are translated to a local origin and the title replaced, so nothing here says
 * where the pattern came from.
 *
 * Do not edit by hand.
 */
export const DEMO_PLAN_XEL = ${JSON.stringify(out)};
`;
writeFileSync('src/format/demo-plan-data.js', js);
console.log(`wrote src/format/demo-plan-data.js`);
console.log(`  ${plan.holes.length} records, translated by E-${minE.toFixed(1)} N-${minN.toFixed(1)}`);
console.log(`  ${(js.length / 1024).toFixed(0)} KB`);
